// import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// import { Montserrat } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/shared/Header";
// import Footer from '@/components/shared/Footer'

// // const inter = Inter({ subsets: ["latin"] });
// const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Smada Store",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${montserrat.className} overflow-x-hidden`}>
//       <Header />
//         {children}
//         <Footer/>
//         </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from '@/components/shared/Footer';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smada Store",
  description: "An e-commerce platform for listing and managing products.",
  openGraph: {
    title: "Smada Store",
    description: "An e-commerce platform for listing and managing products.",
    images: ["/images/og-image.jpg"],
    url: "https://my-ecommerce-platform.com",
  },
  robots: {
    index: true,
    follow: true,
  },
  additionalMeta: [
    {
      name: "robots",
      content: "index, follow",
    },
    {
      rel: "sitemap",
      href: "/sitemap.xml",
      type: "application/xml",
    },
    {
      rel: "robots",
      href: "/robots.txt",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} overflow-x-hidden`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
